CREATE TABLE users (
  id INT PRIMARY KEY AUTO_INCREMENT COMMENT 'id',
  avatar VARCHAR ( 64 ) NOT NULL COMMENT '头像',
  nickname VARCHAR ( 32 ) NOT NULL COMMENT '昵称',
  phone VARCHAR ( 32 ) NOT NULL COMMENT '⼿机号',
  password VARCHAR ( 64 ) NOT NULL COMMENT '密码',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间' 
);