-- 用户表
CREATE TABLE users (
  id VARCHAR(36) PRIMARY KEY,
  avatar VARCHAR(64),
  nickname VARCHAR(32) NOT NULL,
  phone VARCHAR(32),
  password VARCHAR(64) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  email VARCHAR(255) NOT NULL
);

-- 验证码表（没有redis的时候myslq备用）
CREATE TABLE verifiy_codes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  code VARCHAR(6) NOT NULL,
  expire_time DATETIME NOT NULL
);